<a href="https://colab.research.google.com/github/Shimaliza/Coursera--Python-Tasks/blob/main/PY0101EN_5_2_API_2_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Simple APIs
Random User and Fruitvice API Examples

To start using the API you can install the randomuser library running the pip install command.

In [3]:
!pip install randomuser

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting randomuser
  Downloading randomuser-1.6.tar.gz (5.0 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: randomuser
  Building wheel for randomuser (setup.py) ... done
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5080 sha256=ecff8c84bccdc9ddb72ab2763ecad7b045a821fa0eb8911bfa3b281844734af9
  Stored in directory: /root/.cache/pip/wheels/41/6f/23/878c103a235dc2d4e85a3965c124aae8a28470c541b81aa2ba
Successfully built randomuser
Installing collected packages: randomuser
Successfully installed randomuser-1.6

In [4]:
from randomuser import RandomUser
import pandas as pd

First, we will create a random user object, r.

In [3]:
r = RandomUser()

In [4]:
some_list = r.generate_users(10)

In [5]:
some_list

[<randomuser.RandomUser at 0x7f9727536040>,
 <randomuser.RandomUser at 0x7f9727536520>,
 <randomuser.RandomUser at 0x7f9727536100>,
 <randomuser.RandomUser at 0x7f9727536730>,
 <randomuser.RandomUser at 0x7f9727536700>,
 <randomuser.RandomUser at 0x7f9727536880>,
 <randomuser.RandomUser at 0x7f97281bf970>,
 <randomuser.RandomUser at 0x7f9704264d00>,
 <randomuser.RandomUser at 0x7f9704264dc0>,
 <randomuser.RandomUser at 0x7f9704264ac0>]

In [6]:
name = r.get_full_name()

In [7]:
for user in some_list:
    print (user.get_full_name()," ",user.get_email())

Ryan Abraham   ryan.abraham@example.com
Daniel Johansen   daniel.johansen@example.com
Bernard Sullivan   bernard.sullivan@example.com
Lola Kennedy   lola.kennedy@example.com
پریا یاسمی   pry.ysmy@example.com
Lesa Garrett   lesa.garrett@example.com
Damaris Van Bree   damaris.vanbree@example.com
Amna Rahman   amna.rahman@example.com
Brian Clark   brian.clark@example.com
Gaëtan Vincent   gaetan.vincent@example.com

Exercise 1
In this Exercise, generate photos of the random 5 users.

In [8]:
for user in some_list:
    print(user.get_picture())

https://randomuser.me/api/portraits/men/39.jpg
https://randomuser.me/api/portraits/men/72.jpg
https://randomuser.me/api/portraits/men/49.jpg
https://randomuser.me/api/portraits/women/71.jpg
https://randomuser.me/api/portraits/women/92.jpg
https://randomuser.me/api/portraits/women/83.jpg
https://randomuser.me/api/portraits/women/70.jpg
https://randomuser.me/api/portraits/women/58.jpg
https://randomuser.me/api/portraits/men/51.jpg
https://randomuser.me/api/portraits/men/3.jpg

To generate a table with information about the users, we can write a function containing all desirable parameters. For example, name, gender, city, etc. The parameters will depend on the requirements of the test to be performed. We call the Get Methods, listed at the beginning of this notebook. Then, we return pandas dataframe with the users.

def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
      
    return pd.DataFrame(users)     
def get_users():

In [9]:
def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
      
    return pd.DataFrame(users)

In [10]:
get_users()

,Name,Gender,City,State,Email,DOB,Picture
0,Iwan Fournier,male,Eisten,Appenzell Innerrhoden,iwan.fournier@example.com,1982-07-09T22:00:51.466Z,https://randomuser.me/api/portraits/men/7.jpg
1,Jordi Muñoz,male,Palma de Mallorca,País Vasco,jordi.munoz@example.com,1956-03-10T21:05:56.377Z,https://randomuser.me/api/portraits/men/6.jpg
2,Eevi Waisanen,female,Outokumpu,Northern Savonia,eevi.waisanen@example.com,1978-10-17T09:39:17.616Z,https://randomuser.me/api/portraits/women/6.jpg
3,Romeo David,male,Ursins,Luzern,romeo.david@example.com,1988-05-09T06:55:05.950Z,https://randomuser.me/api/portraits/men/43.jpg
4,Emil Tuomala,male,Oulunsalo,Lapland,emil.tuomala@example.com,1982-06-20T23:32:02.838Z,https://randomuser.me/api/portraits/men/82.jpg
5,Wolf Hilmer,male,Schlettau,Schleswig-Holstein,wolf.hilmer@example.com,1951-01-27T21:58:00.044Z,https://randomuser.me/api/portraits/men/25.jpg
6,Deniz Kunt,female,Osmaniye,Muş,deniz.kunt@example.com,1947-02-01T18:45:34.503Z,https://randomuser.me/api/portraits/women/40.jpg
7,Aysel Geelen,female,Zandberg Dr,Drenthe,aysel.geelen@example.com,1955-04-13T07:35:39.393Z,https://randomuser.me/api/portraits/women/58.jpg
8,Liliana Glatz,female,Geisa,Baden-Württemberg,liliana.glatz@example.com,1980-02-12T19:23:26.919Z,https://randomuser.me/api/portraits/women/41.jpg
9,Debra Parker,female,Cobh,Kildare,debra.parker@example.com,1973-08-06T10:28:04.598Z,https://randomuser.me/api/portraits/women/4.jpg

Example 2: Fruitvice API

In [5]:
import requests
import json

We will obtain the fruitvice API data using requests.get("url") function. The data is in a json format.

In [12]:
data = requests.get("https://fruityvice.com/api/fruit/all")

We will retrieve results using json.loads() function.

In [13]:
results = json.loads(data.text)

We will convert our json data into pandas data frame.

In [14]:
pd.DataFrame(results)

,genus,name,id,family,order,nutritions
0,Malus,Apple,6,Rosaceae,Rosales,"{'carbohydrates': 11.4, 'protein': 0.3, 'fat':..."
1,Prunus,Apricot,35,Rosaceae,Rosales,"{'carbohydrates': 3.9, 'protein': 0.5, 'fat': ..."
2,Persea,Avocado,84,Lauraceae,Laurales,"{'carbohydrates': 8.53, 'protein': 2, 'fat': 1..."
3,Musa,Banana,1,Musaceae,Zingiberales,"{'carbohydrates': 22, 'protein': 1, 'fat': 0.2..."
4,Rubus,Blackberry,64,Rosaceae,Rosales,"{'carbohydrates': 9, 'protein': 1.3, 'fat': 0...."
5,Fragaria,Blueberry,33,Rosaceae,Rosales,"{'carbohydrates': 5.5, 'protein': 0, 'fat': 0...."
6,Prunus,Cherry,9,Rosaceae,Rosales,"{'carbohydrates': 12, 'protein': 1, 'fat': 0.3..."
7,Vaccinium,Cranberry,87,Ericaceae,Ericales,"{'carbohydrates': 12.2, 'protein': 0.4, 'fat':..."
8,Selenicereus,Dragonfruit,80,Cactaceae,Caryophyllales,"{'carbohydrates': 9, 'protein': 9, 'fat': 1.5,..."
9,Durio,Durian,60,Malvaceae,Malvales,"{'carbohydrates': 27.1, 'protein': 1.5, 'fat':..."
10,Sellowiana,Feijoa,76,Myrtaceae,Myrtoideae,"{'carbohydrates': 8, 'protein': 0.6, 'fat': 0...."
11,Ficus,Fig,68,Moraceae,Rosales,"{'carbohydrates': 19, 'protein': 0.8, 'fat': 0..."
12,Ribes,Gooseberry,69,Grossulariaceae,Saxifragales,"{'carbohydrates': 10, 'protein': 0.9, 'fat': 0..."
13,Vitis,Grape,81,Vitaceae,Vitales,"{'carbohydrates': 18.1, 'protein': 0.72, 'fat'..."
14,Malus,GreenApple,72,Rosaceae,Rosales,"{'carbohydrates': 3.1, 'protein': 0.4, 'fat': ..."
15,Psidium,Guava,37,Myrtaceae,Myrtales,"{'carbohydrates': 14, 'protein': 2.6, 'fat': 1..."
16,Apteryx,Kiwi,66,Actinidiaceae,Struthioniformes,"{'carbohydrates': 15, 'protein': 1.1, 'fat': 0..."
17,Actinidia,Kiwifruit,85,Actinidiaceae,Ericales,"{'carbohydrates': 14.6, 'protein': 1.14, 'fat'..."
18,Citrus,Lemon,26,Rutaceae,Sapindales,"{'carbohydrates': 9, 'protein': 1.1, 'fat': 0...."
19,Citrus,Lime,44,Rutaceae,Sapindales,"{'carbohydrates': 8.4, 'protein': 0.3, 'fat': ..."
20,Vaccinium,Lingonberry,65,Ericaceae,Ericales,"{'carbohydrates': 11.3, 'protein': 0.75, 'fat'..."
21,Litchi,Lychee,67,Sapindaceae,Sapindales,"{'carbohydrates': 17, 'protein': 0.8, 'fat': 0..."
22,Mangifera,Mango,27,Anacardiaceae,Sapindales,"{'carbohydrates': 15, 'protein': 0.82, 'fat': ..."
23,Cucumis,Melon,41,Cucurbitaceae,Cucurbitaceae,"{'carbohydrates': 8, 'protein': 0, 'fat': 0, '..."
24,Morus,Morus,82,Moraceae,Rosales,"{'carbohydrates': 9.8, 'protein': 1.44, 'fat':..."
25,Citrus,Orange,2,Rutaceae,Sapindales,"{'carbohydrates': 8.3, 'protein': 1, 'fat': 0...."
26,Carica,Papaya,42,Caricaceae,Caricacea,"{'carbohydrates': 11, 'protein': 0, 'fat': 0.4..."
27,Passiflora,Passionfruit,70,Passifloraceae,Malpighiales,"{'carbohydrates': 22.4, 'protein': 2.2, 'fat':..."
28,Prunus,Peach,86,Rosaceae,Rosales,"{'carbohydrates': 9.5, 'protein': 0.9, 'fat': ..."
29,Pyrus,Pear,4,Rosaceae,Rosales,"{'carbohydrates': 15, 'protein': 0.4, 'fat': 0..."
30,Diospyros,Persimmon,52,Ebenaceae,Rosales,"{'carbohydrates': 18, 'protein': 0, 'fat': 0, ..."
31,Ananas,Pineapple,10,Bromeliaceae,Poales,"{'carbohydrates': 13.12, 'protein': 0.54, 'fat..."
32,Cactaceae,Pitahaya,78,Cactaceae,Caryophyllales,"{'carbohydrates': 7, 'protein': 1, 'fat': 0.4,..."
33,Prunus,Plum,71,Rosaceae,Rosales,"{'carbohydrates': 11.4, 'protein': 0.7, 'fat':..."
34,Punica,Pomegranate,79,Lythraceae,Myrtales,"{'carbohydrates': 18.7, 'protein': 1.7, 'fat':..."
35,Rubus,Raspberry,23,Rosaceae,Rosales,"{'carbohydrates': 12, 'protein': 1.2, 'fat': 0..."
36,Fragaria,Strawberry,3,Rosaceae,Rosales,"{'carbohydrates': 5.5, 'protein': 0.8, 'fat': ..."
37,Citrus,Tangerine,77,Rutaceae,Sapindales,"{'carbohydrates': 8.3, 'protein': 0, 'fat': 0...."
38,Solanum,Tomato,5,Solanaceae,Solanales,"{'carbohydrates': 3.9, 'protein': 0.9, 'fat': ..."
39,Citrullus,Watermelon,25,Cucurbitaceae,Cucurbitales,"{'carbohydrates': 8, 'protein': 0.6, 'fat': 0...."

The result is in a nested json format. The 'nutrition' column contains multiple subcolumns, so the data needs to be 'flattened' or normalized.

In [15]:
df2 = pd.json_normalize(results)

In [16]:
df2

,genus,name,id,family,order,nutritions.carbohydrates,nutritions.protein,nutritions.fat,nutritions.calories,nutritions.sugar
0,Malus,Apple,6,Rosaceae,Rosales,11.40,0.30,0.40,52,10.30
1,Prunus,Apricot,35,Rosaceae,Rosales,3.90,0.50,0.10,15,3.20
2,Persea,Avocado,84,Lauraceae,Laurales,8.53,2.00,14.66,160,0.66
3,Musa,Banana,1,Musaceae,Zingiberales,22.00,1.00,0.20,96,17.20
4,Rubus,Blackberry,64,Rosaceae,Rosales,9.00,1.30,0.40,40,4.50
5,Fragaria,Blueberry,33,Rosaceae,Rosales,5.50,0.00,0.40,29,5.40
6,Prunus,Cherry,9,Rosaceae,Rosales,12.00,1.00,0.30,50,8.00
7,Vaccinium,Cranberry,87,Ericaceae,Ericales,12.20,0.40,0.10,46,4.00
8,Selenicereus,Dragonfruit,80,Cactaceae,Caryophyllales,9.00,9.00,1.50,60,8.00
9,Durio,Durian,60,Malvaceae,Malvales,27.10,1.50,5.30,147,6.75
10,Sellowiana,Feijoa,76,Myrtaceae,Myrtoideae,8.00,0.60,0.40,44,3.00
11,Ficus,Fig,68,Moraceae,Rosales,19.00,0.80,0.30,74,16.00
12,Ribes,Gooseberry,69,Grossulariaceae,Saxifragales,10.00,0.90,0.60,44,0.00
13,Vitis,Grape,81,Vitaceae,Vitales,18.10,0.72,0.16,69,16.00
14,Malus,GreenApple,72,Rosaceae,Rosales,3.10,0.40,0.10,21,6.40
15,Psidium,Guava,37,Myrtaceae,Myrtales,14.00,2.60,1.00,68,9.00
16,Apteryx,Kiwi,66,Actinidiaceae,Struthioniformes,15.00,1.10,0.50,61,9.00
17,Actinidia,Kiwifruit,85,Actinidiaceae,Ericales,14.60,1.14,0.50,61,8.90
18,Citrus,Lemon,26,Rutaceae,Sapindales,9.00,1.10,0.30,29,2.50
19,Citrus,Lime,44,Rutaceae,Sapindales,8.40,0.30,0.10,25,1.70
20,Vaccinium,Lingonberry,65,Ericaceae,Ericales,11.30,0.75,0.34,50,5.74
21,Litchi,Lychee,67,Sapindaceae,Sapindales,17.00,0.80,0.44,66,15.00
22,Mangifera,Mango,27,Anacardiaceae,Sapindales,15.00,0.82,0.38,60,13.70
23,Cucumis,Melon,41,Cucurbitaceae,Cucurbitaceae,8.00,0.00,0.00,34,8.00
24,Morus,Morus,82,Moraceae,Rosales,9.80,1.44,0.39,43,8.10
25,Citrus,Orange,2,Rutaceae,Sapindales,8.30,1.00,0.20,43,8.20
26,Carica,Papaya,42,Caricaceae,Caricacea,11.00,0.00,0.40,43,1.00
27,Passiflora,Passionfruit,70,Passifloraceae,Malpighiales,22.40,2.20,0.70,97,11.20
28,Prunus,Peach,86,Rosaceae,Rosales,9.50,0.90,0.25,39,8.40
29,Pyrus,Pear,4,Rosaceae,Rosales,15.00,0.40,0.10,57,10.00
30,Diospyros,Persimmon,52,Ebenaceae,Rosales,18.00,0.00,0.00,81,18.00
31,Ananas,Pineapple,10,Bromeliaceae,Poales,13.12,0.54,0.12,50,9.85
32,Cactaceae,Pitahaya,78,Cactaceae,Caryophyllales,7.00,1.00,0.40,36,3.00
33,Prunus,Plum,71,Rosaceae,Rosales,11.40,0.70,0.28,46,9.92
34,Punica,Pomegranate,79,Lythraceae,Myrtales,18.70,1.70,1.20,83,13.70
35,Rubus,Raspberry,23,Rosaceae,Rosales,12.00,1.20,0.70,53,4.40
36,Fragaria,Strawberry,3,Rosaceae,Rosales,5.50,0.80,0.40,29,5.40
37,Citrus,Tangerine,77,Rutaceae,Sapindales,8.30,0.00,0.40,45,9.10
38,Solanum,Tomato,5,Solanaceae,Solanales,3.90,0.90,0.20,74,2.60
39,Citrullus,Watermelon,25,Cucurbitaceae,Cucurbitales,8.00,0.60,0.20,30,6.00

Let's see if we can extract some information from this dataframe. Perhaps, we need to know the family and genus of a cherry.

In [17]:
cherry = df2.loc[df2["name"] == 'Cherry']
(cherry.iloc[0]['family']) , (cherry.iloc[0]['genus'])

('Rosaceae', 'Prunus')

Exercise 2
In this Exercise, find out how many calories are contained in a banana.

In [20]:
cal_banana = df2.loc[df2["name"] == 'Banana']
cal_banana.iloc[0]['nutritions.calories']

96

Exercise 3

This page contains a list of free public APIs. Choose any API of your interest and use it to load/extract some information, as shown in the example above.

Using requests.get("url") function, load your data

In [6]:
data2 = requests.get("https://www.fishwatch.gov/api/species")

In [7]:
results2 = json.loads(data2.text)

In [8]:
df3 = pd.DataFrame(results2)
df3

,Fishery Management,Habitat,Habitat Impacts,Image Gallery,Location,Management,NOAA Fisheries Region,Population,Population Status,Scientific Name,...,Selenium,Serving Weight,Servings,Sodium,Source,"Sugars, Total",Taste,Texture,Path,last_update
0,"<ul>\n<li><a href=""https://www.fisheries.noaa....",None,"Bottomfish fishing operations, typically using...",[{'src': 'https://origin-east-01-drupal-fishwa...,<ul>\n<li>Crimson jobfish are distributed thro...,None,Pacific Islands,"The population level is unknown, but the stock...",<ul>\n<li>There are five stocks of crimson job...,Pristipomoides filamentosus,...,38.2 mcg,100 g (raw),1,64 mg,<p>U.S -wild caught around Hawaii and Pacific ...,0 g,<p>Crimson jobfish has a delicate flavor.</p>\n,<p>Crimson jobfish has&nbsp;a firm texture and...,/profiles/crimson-jobfish,06/21/2022 - 12:00
1,"<ul>\n<li><a href=""https://www.fisheries.noaa....","<ul>\n<li>White hake are groundfish, meaning t...",Area closures and gear restrictions protect ha...,[{'src': 'https://origin-east-01-drupal-fishwa...,<ul>\n<li>White hake are found in the northwes...,None,Greater Atlantic,The stock is not overfished.,<ul>\n<li>According to the 2022&nbsp;stock ass...,Urophycis tenuis,...,32.1 mcg,100 g (raw),1,72 mg,<p>White hake is wild-caught from Maine to sou...,0 g,"<p>White hake has a mild, almost sweet&nbsp;ta...","<p>White hake has a soft, delicate texture tha...",/profiles/white-hake,01/11/2023 - 17:11
2,"<ul>\n<li>\n<p><a href=""https://archive.fisher...",<ul>\n<li>Atlantic chub mackerel are a schooli...,Area closures and gear restrictions protect ha...,[{'src': 'https://origin-east-01-drupal-fishwa...,<ul>\n<li>Atlantic chub mackerel in the wester...,None,Greater Atlantic,"The population level is unknown, but manageme...",<p>Atlantic chub mackerel has never been asses...,Scomber colias,...,44.1 mcg,100 g (raw),1,90 mg,<p>U.S. wild caught from Southern New England ...,0 g,"<p>Rich, pronounced flavor.</p>\n","<p>Soft, flaky, and moist.</p>\n",/profiles/atlantic-chub-mackerel,01/25/2023 - 09:57
3,"<ul>\n<li><a href=""https://www.fisheries.noaa....",<ul>\n<li>Shortfin squid live in deep and shal...,Fishing gears used to harvest shortfin squid h...,None,<ul>\n<li>Shortfin squid inhabits the continen...,None,Greater Atlantic,"The population level is unknown, but managemen...",<ul>\n<li>According to the latest assessment (...,Illex illecebrosus,...,44.8 mcg,100 g,1,44 mg,<p>U.S. wild-caught from Maine to North Caroli...,0 g,"<p>Mild, and subtly sweet.</p>\n<p>&nbsp;</p>\n",<p>Firm and meaty.</p>\n,/profiles/shortfin-squid,01/24/2023 - 12:42
4,"<ul>\n<li>The states and <a href=""https://www....",<ul>\n<li>American lobsters live on the ocean ...,Fishing gears used to harvest American lobster...,[{'src': 'https://origin-east-01-drupal-fishwa...,<ul>\n<li>American lobsters are found in the n...,None,Greater Atlantic,The Gulf of Maine/Georges Bank stock is not ov...,"<ul>\n<li>According to the 2020&nbsp;<a href=""...",Homarus americanus,...,41.4 mcg,100 g (raw),1,296 mg,<p>U.S. wild-caught from Maine to North Caroli...,0 g,<p>Mild and sweet.</p>\n,<p>The meat is firm and somewhat fibrous. The ...,/profiles/american-lobster,01/26/2023 - 15:22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,"<ul>\n<li><a href=""https://www.fisheries.noaa....",<ul>\n<li>Younger pollock live in the mid-wate...,The Alaska pollock fishery uses midwater trawl...,[{'src': 'https://origin-east-01-drupal-fishwa...,<ul>\n<li>Alaska pollock are found throughout ...,None,Alaska,"The Aleutian Islands, Eastern Bering Sea, and ...",<ul>\n<li>There are five stocks of walleye pol...,Gadus chalcogrammus,...,21.9 mcg,100 g (raw),1,99 mg,"<p>U.S. wild-caught, mainly in the Bering Sea ...",0 g,<p>Pollock has mild-tasting flesh and is simil...,<p>Pollock has a relatively fine texture and i...,/profiles/alaska-pollock,01/20/2023 - 15:00
112,"<ul>\n<li><a href=""https://www.greateratlantic...","<ul>\n<li>Monkfish live on the ocean floor, ty...",Area closures and gear restrictions protect ha...,[{'src': 'https://origin-east-01-drupal-fishwa...,<ul>\n<li>Monkfish are found in the Northwest ...,None,"Greater Atlantic, Southeast",The population level is unknown and management...,<ul>\n<li>There are two stocks of monkfish: Gu...,Lophius americanus,...,36.5 mcg,100 g (raw),1,18 mg,<p>U.S. wild-caught from Maine to North Caroli...,0 g,<p>Mild.</p>\n,"<p>The tail meat is firm, dense, and relativel...",/profiles/monkfish,01/11/2023 - 15:47
113,"<ul>\n<li><a href=""http://sero.nmfs.noaa.gov/""...",<ul>\n<li>Mahi mahi live near the surface in t...,Fishing gear used to catch mahi mahi rarely co...,[{'src': 'https://origin-east-01-drupal-fishwa...,"<ul>\n<li>Mahi mahi are found in the Atlantic,...",None,"Greater Atlantic, Southeast",The South Atlantic stock is not overfished.,<p>There are two stocks of dolphinfish: a Sout...,Coryphaena hippurus,...,36.5 mcg,100 g (raw),1,88 mg,<p>Wild-caught from Massachusetts to Texas.</p>\n,0 g,"<p>Mahi mahi has a sweet, mild flavor. For a m...",<p>Mahi mahi is lean and fairly firm with larg...,/profiles/atlantic-mahi-mahi,01/26/2023 - 14:51
114,"<ul>\n<li><a href=""https://sero.nmfs.noaa.gov/...",<ul>\n<li>Cobia are found near structures in t...,Fishing gear used to catch cobia rarely contac...,[{'src': 'https://origin-east-01-drupal-fishwa...,"<ul>\n<li>In U.S. waters, cobia are most abund...",None,"Greater Atlantic, Southeast",The stock is not overfished.,<ul>\n<li>\n<p>According to the 2020 stock ass...,Rachycentron canadum,...,36.5 mcg,100 g (raw),1,135 mg,<p>Wild-caught from Virginia to Texas. Cobia i...,0 g,"<p>Cobia has a sweet, rich flavor.</p>\n","<p>Cobia is lean, moist, and firm with a nice ...",/profiles/cobia,01/18/2023 - 12:23
115,<ul>\n<li>There are two stocks of Atlantic cod...,<ul>\n<li>Atlantic cod live near the ocean flo...,Area closures and gear restrictions protect ha...,[{'src': 'https://origin-east-01-drupal-fishwa...,"<ul>\n<li>In the Northwest Atlantic, cod range...",None,Greater Atlantic,The Gulf of Maine and Georges Bank stocks are ...,<ul>\n<li>There are two stocks of Atlantic cod...,Gadus morhua,...,33.1 mcg,100 g,1,54 mg,<p>Wild-caught from Maine to Virginia.</p>\n,0 g,<p>Atlantic cod has a mild clean flavor. It is...,<p>Cod has large flakes. It's less firm than h...,/profiles/atlantic-cod,01/19/2023 - 17:28